In [1]:
import numpy as np

In [2]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [3]:
np.ones((1,2))

array([[1., 1.]])

In [4]:
np.random.randint(1,3)

1

In [5]:
np.random.randint(0,100,((3,4)))

array([[98, 71, 96, 86],
       [95, 34, 75, 57],
       [79, 35, 42, 91]])

In [7]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [10]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [11]:
np.random.seed(101)

In [12]:
np.random.randint(0,101,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [13]:
arr= np.random.randint(0,100,10)

In [14]:
arr

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [15]:
arr.max()

93

In [16]:
arr.min()

4

In [17]:
arr.mean()

47.3

In [18]:
arr.argmax()

8

In [19]:
arr.argmin()

0

In [21]:
arr.reshape(5,2)

array([[ 4, 63],
       [40, 60],
       [92, 64],
       [ 5, 12],
       [93, 40]])

In [28]:
matt=np.arange(0,100).reshape(10,10)

In [29]:
matt

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
a=np.linspace(0,100,101)

In [37]:
a

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [38]:
matt[5,2]

52

In [42]:
matt[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [43]:
import pandas as pd

In [44]:
df_s= pd.read_csv("")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 26, saw 371
